version: '3.4'
services:

  # DynDNS client

  ddclient-cloudflare:
    image: rycus86/ddclient
    command: --daemon=300 --ssl --debug --file /var/config/ddclient/ddclient-cloudflare.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.priority == low
    volumes:
      - ddclient-config:/var/config/ddclient:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.0.52:24224
        fluentd-async-connect: 'true'
        tag: app.ddclient.cloudflare

volumes:
  ddclient-config:
    driver: local
    driver_opts:
      type: nfs
      device: :/mnt/shared/home-stack/dns
      o: addr=192.168.0.52,rsize=8192,wsize=8192,timeo=15,hard,intr
