version: '3.5'
services:

  domain-automation:
    image: rycus86/domain-automation
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 64M
      update_config:
        failure_action: rollback
      labels:
        - prometheus-job=domain-automation
        - prometheus-port=9421
    environment:
      DOCKER_HOST: tcp://docker-manager:2375
    secrets:
      - source: domain-automation-settings
        target: /var/secrets/app.config
      - source: cloudflare-config
        target: /var/secrets/cloudflare
      - source: certbot-config
        target: /var/secrets/certbot
      - source: notification-config
        target: /var/secrets/notifications
    networks:
      - monitoring
      - docker
    volumes:
      - ssl-certs:/etc/letsencrypt:nocopy
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.0.52:24224
        fluentd-async-connect: 'true'
        fluentd-sub-second-precision: 'true'
        tag: app.domain.automation

secrets:
  domain-automation-settings:
    name: domain-automation-${DOMAIN_AUTOMATION_SETTINGS}
    file: ./config/domain-automation.settings
  cloudflare-config:
    name: cloudflare-config-${CLOUDFLARE_CONF}
    file: ./config/cloudflare.conf
  certbot-config:
    name: certbot-config-${CERTBOT_CONF}
    file: ./config/certbot.conf
  notification-config:
    name: notification-config-${NOTIFICATIONS_CONF}
    file: ./config/notifications.conf

volumes:
  ssl-certs:
    driver: local
    driver_opts:
      type: nfs4
      device: :/ssl-certs
      o: addr=192.168.0.52,rsize=8192,wsize=8192,timeo=15,hard,intr

networks:
  monitoring:
    name: home-monitoring
    external: true
  docker:
    name: home-docker
    external: true
