version: '3.4'
services:

  # DynDNS client

  ddclient-cloudflare:
    image: rycus86/ddclient
    command: --daemon=300 --ssl --debug
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.priority == low
    volumes:
      - ddclient-config:/etc/ddclient.conf:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.0.52:24224
        fluentd-async-connect: 'true'
        tag: app.ddclient.cloudflare

volumes:
  ddclient-config:
    driver: local
    driver_opts:
      type: nfs4
      device: :/home-stack/dns/ddclient-cloudflare.conf
      o: addr=192.168.0.52,rsize=8192,wsize=8192,timeo=14,intr
